name: Compile documents
on: workflow_dispatch

jobs:
  compile-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile multiple Typst documents
        uses:  lvignoli/typst-action@main
        with:
          source_file: |
            junioren-a.typ
            junioren-b.typ
            aktive.typ
